#!/usr/bin/perl -w

my ${prefix}="/usr/local/nagtrap";

my ${exec_prefix}="${prefix}";

my ${datarootdir}="${prefix}/share";

my ${datadir}="${datarootdir}";

my $PERL="/usr/bin/perl";

my $INSTALL="/usr/bin/install -c";
if($INSTALL =~ /^\.\//){
    $INSTALL =~ s/^\.\//\.\.\//;
}
my $INSTALL_OPTS="-o nagios -g nagios";
my $PKG_REL_DATE="31-05-2012";
my $PKG_VERSION="1.5.0";
my $PKG_NAME="nagtrap";
my $HTTPD_CONF="/etc/httpd/conf.d";
my $htmurl="/nagtrap";
my $monitoring_user="nagios";
my $monitoring_grp="nagios";
my $monitoring_installdir="/usr/local/nagios";
my $monitoring_libexecdir="/usr/local/nagios/libexec";
my $basic_authname = "Nagios Access";
if ($monitoring_installdir =~ /icinga/) {
	$basic_authname = "Icinga Access";
}
my $htpasswdusers_file="no";
my $libexecdir="${exec_prefix}/libexec";
my $sysconfdir="${prefix}/etc";
my $localstatedir="${prefix}/var";
my $logdir="${prefix}/var/log";
my $host_os="linux-gnu";
my $ac_configure_args="";

my $srcdir=".";

# my $CP="@CP@";

while ($f = shift @ARGV) {

	if (-x "/bin/mktemp") { 
		$TEMP = `/bin/mktemp $f.$$.XXXXXX`;
		die 'Cannot make temporary file $TEMP' if($?);
		chomp $TEMP;
	} else {
		$XXXXXX = rand;
		$TEMP = "$f.$$.$XXXXXX";
	}

	open(IN,"<$f.in");
	open(OUT,">$TEMP") || die 'Cannot make temporary file $TEMP';

	while (<IN>) {
		s|\@monitoring_user\@|$monitoring_user|g;
		s|\@monitoring_grp\@|$monitoring_grp|g;
		s|\@monitoring_installdir\@|$monitoring_installdir|g;
		s|\@monitoring_libexecdir\@|$monitoring_libexecdir|g;
		s|\@basic_authname\@|$basic_authname|g;
		s|\@htpasswdusers_file\@|$htpasswdusers_file|g;
		s|\@libexecdir\@|$libexecdir|g; # put all --with-vars before directories
		s|\@localstatedir\@|$localstatedir|g;
		s|\@logdir\@|$logdir|g;
		s|\@sysconfdir\@|$sysconfdir|g;
		s|\@htmurl\@|$htmurl|g;
		s|\@datarootdir\@|$datarootdir|g;
		s|\@datadir\@|$datadir|g;
		s|\@PKG_VERSION\@|$PKG_VERSION|g;
		s|\$\{exec_prefix\}|$exec_prefix|g; # must be next to last
		s|\$\{prefix\}|$prefix|g; # must be last
		print OUT $_;
	}

	close IN;
	close OUT;

	if ((! -e $f) || (`diff $f $TEMP`)) {
		`mv $TEMP $f`;
	} else {
	         unlink $TEMP;
	}

}
